### ISSUE TITLE
Add maven or gradle to project for compiling project to 'jar' file

### ISSUE THREAD

**Issue by Slimercorp** [andrew116st/Battleship#20]
Now you can run the game only in the IDEA IDE. It's need to use system of assembly, which will compile your code and collect it to jar file. It will allow to run your game on any computer, which has Java JRE. Such systems of assembly is named 'Gradle' or 'Maven'. You can choose any of it.

**Comment by andrew116st** [comment]
https://github.com/andrew116st/Battleship/pull/24
