### ISSUE TITLE
Refactoring: Rewrite project using object oriented programming

### ISSUE THREAD

**Issue by Slimercorp** [andrew116st/Battleship#22]
At the current moment the project don't use object oriented programming. It's functional programming. We need to go further and learn write project based on objects. It's not easy. First of all, you need create a first approximation of object architecture. I suggest to use as object - map of battleship. You need to describe properties and methods, which it should has. I will help you.

**Comment by Slimercorp** [comment]
class BattleShipGame
properties:
String[] myShips; //карта, где будут расставлены мои корабли
String[] enemyMap; //карта, где я буду отмечать куда я стрелял у противника.

methods:
1) BattleShipGame(String[] myShips); // конструктор, в котором передается уже готовая карта! Она может быть снаружи создана "по умолчанию", с помощью сканнера или как то еще. Также тут инициализируется карта enemyMap

2) void showEnemyMap(); //Печатает карту на экран противнику с моими отметками

3) void showMyMap(); //Печатает мою карту на экран (возможно пригодится, возможно нет)

4) int hit(int x, int y); //Принимает удар по своей карте по координатам, выдает результат в виде числа int: 0 - промах, 1 - ранил, 2 - потопил. Пока int, потом заменим на enum. Отмечаем на своей карте подбитый корабль красным квадратом, считаем кол-во подбитых своих кораблей, если промах - ничего не делаем, только возвращаем 0.  (поле myShips у нас).

5) void writeResult(int x, int y, int result); //Записываем у себя на карте результат своей попытки удара (до этого мы вызвали на объекте противника метод hit). Ставим у себя точку или красный квадрат (поле enemyMap у нас).

6) int getDestroyedShips(); //возвращаем количество подбитых кораблей. Нужно для определения конца игры.

Думаю этого пока достаточно для первого шага рефакторинга

**Comment by andrew116st** [comment]
https://github.com/andrew116st/Battleship/pull/26
